Add read-only support
editor-js/checklist pull request #13
Opened 2020-08-22 22:30 UTC by gohabereg

2020-08-23 17:49 UTC, gohabereg commented on src/index.js
> +    //
Хз, линтер пофиксил

2020-08-23 18:21 UTC, talyguryn approved these changes

2020-09-29 20:24 UTC, khaydarov requested changes

2020-09-29 20:24 UTC, khaydarov commented on src/index.js
>     * @public
```suggestion
```

2020-09-29 20:24 UTC, khaydarov commented on src/index.js
>     * @public
```suggestion
```

2020-09-29 20:28 UTC, neSpecc commented on src/index.js
> +     * If read-only mode is on, fo not bind events
```suggestion
     * If read-only mode is on, do not bind events
```

2020-09-29 20:29 UTC, neSpecc approved these changes

2020-09-29 20:40 UTC, khaydarov approved these changes

2020-09-29 20:43 UTC, merged